import type { Dispatch, RefObject, SetStateAction } from 'react';
import type Hls from 'hls.js';
import type { PlaylistItem } from '../utils/m3uParser';
import type { PlaybackStatus, PlayerQualityLevel } from './cinematicPlayerHelpers';
import type { LearnedIntro, SessionAudioTrack } from './cinematicPlayerSessionHelpers';
import type { CinematicSubtitleTrack } from './useCinematicPlayerSubtitles';

export type MutableSessionRef<T> = { current: T };
type Setter<T> = Dispatch<SetStateAction<T>>;

export interface CinematicPlayerSessionContext {
  selectedChannel: PlaylistItem | null;
  saveWatchProgress: (item: PlaylistItem, time: number, total: number) => void;
  showToast: (message: string) => void;
  language: 'tr' | 'en';
  videoReady: boolean;
  videoRef: RefObject<HTMLVideoElement | null>;
  hlsInstanceRef: MutableSessionRef<Hls | null>;
  seekOffsetRef: MutableSessionRef<number>;
  isTranscodingRef: MutableSessionRef<boolean>;
  localBrowserSafeRef: MutableSessionRef<boolean>;
  probedVideoCodecRef: MutableSessionRef<string>;
  activeAudioStreamIdRef: MutableSessionRef<number | undefined>;
  seekRequestIdRef: MutableSessionRef<number>;
  seekTimeoutRef: MutableSessionRef<ReturnType<typeof setTimeout> | null>;
  startupTimeoutRef: MutableSessionRef<ReturnType<typeof setTimeout> | null>;
  recoveryAttemptRef: MutableSessionRef<number>;
  lastRecoveryTimeRef: MutableSessionRef<number>;
  hlsNetworkRecoveriesRef: MutableSessionRef<number>;
  hlsMediaRecoveriesRef: MutableSessionRef<number>;
  lastBufferedUpdateRef: MutableSessionRef<number>;
  seekGraceUntilRef: MutableSessionRef<number>;
  lastRequestedSeekRef: MutableSessionRef<number | null>;
  lastFfmpegRestartAtRef: MutableSessionRef<number>;
  ffmpegRestartInFlightRef: MutableSessionRef<boolean>;
  forcedTranscodeModeRef: MutableSessionRef<'copy' | 'full' | null>;
  pausedTimeRef: MutableSessionRef<number | null>;
  resumeTimeRef: MutableSessionRef<number | null>;
  learnedIntroRef: MutableSessionRef<LearnedIntro | null>;
  playbackSpeedRef: MutableSessionRef<number>;
  playerVolumeRef: MutableSessionRef<number>;
  playerMutedRef: MutableSessionRef<boolean>;
  durationRef: MutableSessionRef<number>;
  invokeFfmpegProxy: (startTime?: number, audioStreamId?: number) => Promise<any>;
  getTranscodeMode: () => 'copy' | 'full';
  forceUnmute: () => void;
  handlePlayerSeek: (time: number, isRelative?: boolean) => void;
  resetSubtitles: () => void;
  setIsPlaying: Setter<boolean>;
  setCurrentTime: Setter<number>;
  setDuration: Setter<number>;
  setFfmpegFallbackActive: Setter<boolean>;
  setBufferedProgress: Setter<number>;
  setVideoReady: Setter<boolean>;
  setPlaybackStatus: Setter<PlaybackStatus>;
  setPlaybackMessage: Setter<string>;
  setQualityLevels: Setter<PlayerQualityLevel[]>;
  setActiveQualityLevel: Setter<number>;
  setAudioTracks: Setter<SessionAudioTrack[]>;
  setActiveAudioTrack: Setter<number>;
  setSubtitleTracks: Setter<CinematicSubtitleTrack[]>;
  setActiveSubtitle: Setter<number>;
  setLearnedIntro: Setter<LearnedIntro | null>;
  setShowIntroSkip: Setter<boolean>;
}
