import type { CSSProperties, ChangeEvent, MouseEvent, RefObject } from 'react';
import type { PlayerQualityLevel } from '../../hooks/useCinematicPlayer';
import type { PlaylistItem } from '../../utils/m3uParser';

export interface CinematicPlayerProps {
  channel: PlaylistItem;
  videoRef: RefObject<HTMLVideoElement | null>;
  playerContainerRef: RefObject<HTMLDivElement | null>;
  isPlaying: boolean;
  currentTime: number;
  duration: number;
  playerVolume: number;
  playerMuted: boolean;
  showControls: boolean;
  videoReady: boolean;
  playbackStatus: 'loading' | 'playing' | 'recovering' | 'transcoding' | 'seeking' | 'error';
  playbackMessage: string;
  playbackSpeed: number;
  showSpeedMenu: boolean;
  qualityLevels: PlayerQualityLevel[];
  activeQualityLevel: number;
  audioTracks: { id: number; name: string; lang: string }[];
  activeAudioTrack: number;
  subtitleTracks: { label: string; srclang: string; src: string }[];
  activeSubtitle: number;
  showSubtitleMenu: boolean;
  isFullscreen: boolean;
  bufferedProgress?: number;
  accentStyles: CSSProperties;
  onClose: () => void;
  onTogglePlay: () => void;
  onToggleMute: () => void;
  onVolumeChange: (event: ChangeEvent<HTMLInputElement>) => void;
  onSpeedChange: (speed: number) => void;
  onQualityChange: (levelId: number) => void;
  onAudioTrackChange: (id: number) => void;
  onSubtitleChange: (index: number) => void;
  onSubtitleUpload: (event: ChangeEvent<HTMLInputElement>) => void;
  onPiP: () => void;
  onToggleFullscreen: () => void;
  onTimelineSeek: (event: MouseEvent<HTMLDivElement>) => void;
  onSeek: (time: number, isRelative?: boolean) => void;
  onHideControls: () => void;
  onShowSpeedMenu: (show: boolean) => void;
  onShowSubtitleMenu: (show: boolean) => void;
  formatTime: (time: number) => string;
  onMouseMove?: () => void;
  onMouseLeave?: () => void;
  channels: PlaylistItem[];
  onChannelChange: (channel: PlaylistItem) => void;
  showIntroSkip?: boolean;
  onSkipIntro?: () => void;
}
